[build]
# rustc-wrapper = '/home/ctronp/.cargo/bin/sccache'
rustc = "rustc"
incremental = false

[target.x86_64-unknown-linux-gnu]
rustflags = [
  '-Copt-level=3',
  '-Ccodegen-units=1',
  '-Ctarget-cpu=native',
  '-Cembed-bitcode=yes',
]

[env]
CC = "clang"
CXX = "clang++"
LD = "lld"
LDFLAGS = "-fuse-ld=lld"
RUSTFLAGS="-Copt-level=3 -Ccodegen-units=1 -Ctarget-cpu=native -Cembed-bitcode=yes"
RUSTCFLAGS = "-Copt-level=3 -Ccodegen-units=1 -Ctarget-cpu=native -Cembed-bitcode=yes"
CARGO_PROFILE_RELEASE_CODEGEN_UNITS = "1"
CARGO_PROFILE_RELEASE_DEBUG = "false"
CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS = "false"
CARGO_PROFILE_RELEASE_INCREMENTAL = "false"
CARGO_PROFILE_RELEASE_LTO = "true"
CARGO_PROFILE_RELEASE_OVERFLOW_CHECK = "false"
CARGO_PROFILE_RELEASE_OPT_LEVEL = "3"
CARGO_PROFILE_RELEASE_PANIC = "abort"

[profile.dev]
opt-level = 0
debug = 2
incremental = true
codegen-units = 512

[profile.release]
strip = true
opt-level = 3
debug = 0
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release.build-override]
strip = false
opt-level = 3
debug = 0
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
