[build]
rustc = "rustc"

[env]
RUSTFLAGS = "-C opt-level=3 -C codegen-units=1 -C target-cpu=native -C linker-plugin-lto -C linker=ld.lld -C link-arg=-fuse-ld=lld -C embed-bitcode=yes"
CC = "clang -flto -O3 -march=native -mtune=native"
CXX = "clang++ -flto -O3 -march=native -mtune=native"
LD = "ld.lld"
CFLAGS = "-O3 -flto -march=native"
CXXFLAGS = "-O3 -flto -march=native"
LDFLAGS = "-fuse-ld=lld"
NUM_JOBS = "1"
CARGO_PROFILE_RELEASE_CODEGEN_UNITS = "1"
CARGO_PROFILE_RELEASE_DEBUG = "false"
CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS = "false"
CARGO_PROFILE_RELEASE_INCREMENTAL = "false"
CARGO_PROFILE_RELEASE_LTO = "true"
CARGO_PROFILE_RELEASE_OVERFLOW_CHECK = "false"
CARGO_PROFILE_RELEASE_OPT_LEVEL = "3"
CARGO_PROFILE_RELEASE_PANIC = "abort"


[profile.release]
strip = true
opt-level = 3
debug = false
split-debuginfo = "..."
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.release.build-override]
strip = true
opt-level = 3
debug = false
split-debuginfo = "..."
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1
