[build]
jobs = 1
rustc = "rustc"

[env]
RUSTFLAGS = "-C opt-level=3 -C codegen-units=1 -C target-cpu=native -C linker-plugin-lto -C linker=clang -C link-arg=-fuse-ld=lld -C embed-bitcode=yes"
CC = "clang -flto -O3 -march=native"
CXX = "clang++ -flto -O3 -march=native"
CFLAGS = "-O3 -flto -march=native"
CXXFLAGS = "-O3 -flto -march=native"
LDFLAGS = "-fuse-ld=lld"
NUM_JOBS = "1"
CARGO_PROFILE_RELEASE_CODEGEN_UNITS = "1"
CARGO_PROFILE_RELEASE_DEBUG = "false"
CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS = "false"
CARGO_PROFILE_RELEASE_INCREMENTAL = "false"
CARGO_PROFILE_RELEASE_LTO = "true"
CARGO_PROFILE_RELEASE_OVERFLOW_CHECK = "false"
CARGO_PROFILE_RELEASE_OPT_LEVEL = "3"
CARGO_PROFILE_RELEASE_PANIC = "abort"
